staticSites:
  - name: geodais-web
    buildCommand: npm install && npm run build
    publishPath: dist/geodais-web/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
