services:
  - type: web
    name: geodais-web
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist/geodais-web/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
